#excerise 11
print("Exercise 11: Multi-Axis IMU Data Processing")
import numpy as np
data = np.array([0.1, 0.2, 9.8, 0.15, 0.22, 9.78, 0.12, 0.21, 9.81, 0.11, 0.23, 9.79])
print("Shape:", data.shape)
print("Dtype:", data.dtype)
reshaped_data = data.reshape(4, 3)
print("IMU matrix:\n", reshaped_data)
print("Total elements:", reshaped_data.size)
#exercise 12
print("Exercise 12: Sensor Fusion & Sorting")
sensor_left = np.array([1.5,0.8,2.3])
sensor_right = np.array([2.1,0.5,1.9])
all_readings = np.concatenate((sensor_left, sensor_right))
print("All sensor readings:", all_readings)
sorted_readings = np.sort(all_readings)
print("Sorted sensor readings:", sorted_readings)
reshaped_data = all_readings.reshape(3, 2)
print("Reshaped sensor data:\n", reshaped_data)
#exercise 13
print("Exercise 13: Robot Sensor Data Extraction")
period_1 = np.array([[10,11,12],[20,21,22]])
period_2 = np.array([[30,31,32],[40,41,42]])
full_data= np.vstack((period_1, period_2))
print("Full sensor data:\n", full_data)
print("Slicing:")
print(full_data[:, 1])
print("Indexing:")
print(full_data[2:4, 1:3])
data_backup = full_data.copy()
print("Data backup:\n", data_backup)
#exercise 14
print("Exercise 14: Sensor Bias Correction")
raw_acel=np.array([[0.1, 0.1, 9.9], [0.1, 0.1, 9.9], [0.2, 0.0, 9.8], [0.1, 0.2, 9.9]])
bias=np.array([0.1, 0.1, 9.8])
cleaned_acel = raw_acel - bias
print("Cleaned accelerometer data:\n", cleaned_acel)
convert=cleaned_acel * 9.81
print("Converted g to m/s^2:\n", convert)
#exercise 15
print("Exercise 15: System Performance Analysis")
rng = np.random.default_rng()
power_consumption = rng.uniform(0.0, 10.0, size=(4,5))
print("Power consumption data:\n", power_consumption)
total_power = np.sum(power_consumption)
print(f"Total power consumption: {total_power:.2f}")
average_power = np.mean(power_consumption,axis=1)
print(f"Average power consumption: {average_power}")
peak_power = np.max(power_consumption,axis=0)
print(f"Peak power consumption: {peak_power}")
transposed_data = power_consumption.reshape(5,4)
print("Transposed data:\n", transposed_data)
#exercise 16
print("Exercise 16: Random Numbers and Statistics")
rng = np.random.default_rng()
matrix=rng.uniform(0.0, 1.0, size=(5,5))
print("Matrix:\n", matrix)
mean_value = np.mean(matrix)
std_value = np.std(matrix)
print(f"Mean value: {mean_value:.2f}, Std detection: {std_value:.2f}")
max_value = np.max(matrix)
print("Row maxs:", matrix.max(axis=1))
#exercise 17
print("Exercise 17: Filtering and Unique Counts")
data=rng.integers(1, 6, size=20)
print("Data:", data)
print("Filtered:",data[data > 3])
values, counts = np.unique(data, return_counts=True)
print("Unique values:", values)
print("Counts:", counts)
#exercise 18
print("Exercise 18: CSV Data Processing")
import pandas as pd
data=rng.random((10,3))
print("Sensor data:\n", data)
np.savetxt('sensor_data.csv', data, delimiter=',', header='Time,Temp,Volt', comments='')
df=pd.read_csv('sensor_data.csv')
print("First 5 rows:\n", df.head())
average_temp = round(df['Temp'].mean(),1)
print(f"Average temperature: {average_temp:.2f}")

